### ISSUE TITLE
Summary- meets expectations

### ISSUE THREAD

**Issue by ghost** [ananthsuresh30/CapstoneProject#5]
Great job with the colmar academy site! You have good indentation and alt attributes, just add more comments. As a next step, consider adding a text box to the site so that users can enter text. You can also add another page to the site. I think you're ready for it!

**Comment by ananthsuresh30** [comment]
yo, thnx a lot

**Comment by ananthsuresh30** [comment]
> Great job with the colmar academy site! You have good indentation and alt attributes, just add more comments. As a next step, consider adding a text box to the site so that users can enter text. You can also add another page to the site. I think you're ready for it!
